services:
  northwindstore.app:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DB=Data Source=northwindstore.db,1433; Initial Catalog=Northwind; User ID=sa; Password=DevPass_1
    ports:
      - "5001:80"
    volumes:
    - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  northwindstore.db:
    ports: 
    - "51446:1433"
    volumes:
      - c:/temp/sqldata:/var/opt/mssql/data